# Generated by Django 2.1.2 on 2018-11-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('author', models.CharField(max_length=200, verbose_name='Author Username')),
                ('url', models.URLField(verbose_name='Project Repository URL')),
                ('irc', models.URLField(verbose_name='Chat URL')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='projects.tag', verbose_name='Project Tag'),
        ),
    ]
