# Generated by Django 2.1.2 on 2018-11-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181110_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colors',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Colour (HEX with #)'),
        ),
    ]
